### ISSUE TITLE
Clone schema fails when functions are in public

### ISSUE THREAD

**Issue by ZipBrandon** [denishpatel/pg-clone-schema#100]
I am attempting to clone a schema with this script which utilizes functions that reside in public.  I see that in your **Limitations** section that you refer to schema-qualified objects will still reference the original schema which is what I think I would want.  Am I missing a parameter to make this work?

`Query 1 ERROR: ERROR:  Action: Tables  Diagnostics: line=PL/pgSQL function clone_schema(text,text,cloneparms[]) line 676 at EXECUTE. 42704. type "new_schema2.citext" does not exist
CONTEXT:  PL/pgSQL function clone_schema(text,text,cloneparms[]) line 2114 at RAISE`

**Comment by MichaelDBA** [comment]
I need more info to analyze your error.  Let me see your calling syntax, plz.

**Comment by lorinkoz** [comment]
I will chime in here:

@ZipBrandon is calling the stored procedure through https://github.com/lorinkoz/django-pgschemas/blob/update-clone-sql/django_pgschemas/utils.py#L195

**Comment by MichaelDBA** [comment]
What version of pg_clone_schema are you running?

**Comment by lorinkoz** [comment]
That was fast! Thank you!
