### ISSUE TITLE
Partitioned Tables

### ISSUE THREAD

**Issue by danieluisilva** [denishpatel/pg-clone-schema#103]
Hi, 

When I was using this script to copy a schema with partitioned tables, I noticed two problems:

1. In loop for child tables and alter them to attach to parent for specific partition method. We need filter partitioned tables of current table

SELECT quote_ident(dest_schema) || '.' || c1.relname as tablename, pg_catalog.pg_get_expr(c1.relpartbound, c1.oid) as partrange, quote_ident(dest_schema) || '.' || c2.relname as object
        FROM pg_catalog.pg_class c1, pg_namespace n, pg_catalog.pg_inherits i, pg_class c2
        WHERE n.nspname = quote_ident(source_schema) **AND c2.relname = quote_ident(tblname)** AND c1.relnamespace = n.oid AND c1.relkind = 'r' AND
        c1.relispartition AND c1.oid=i.inhrelid AND i.inhparent = c2.oid AND c2.relnamespace = n.oid ORDER BY pg_catalog.pg_get_expr(c1.relpartbound, c1.oid) = 'DEFAULT',
        c1.oid::pg_catalog.regclass::pg_catalog.text

Other way, it's tries create partitions for all tables and not just the current one.

2. When we are creating the FK we have to exclude the partitioned tables, if not we get an error that the FK already exists

    SELECT 'ALTER TABLE ' || quote_ident(dest_schema) || '.' || quote_ident(rn.relname)
                          || ' ADD CONSTRAINT ' || quote_ident(ct.conname) || ' ' || REPLACE(pg_get_constraintdef(ct.oid), 'REFERENCES ' || quote_ident(source_schema) || '.', 'REFERENCES ' 
                          || quote_ident(dest_schema) || '.') || ';'
    FROM pg_constraint ct
    JOIN pg_class rn ON rn.oid = ct.conrelid
    **LEFT JOIN pg_inherits i ON (rn.oid = i.inhrelid)**
    WHERE connamespace = src_oid
        AND rn.relkind = 'r'
        AND ct.contype = 'f'
        **AND i.inhrelid is  null**

Cheers, 
Daniel Silva

**Comment by MichaelDBA** [comment]
will try to look at this this weekend...

**Comment by danieluisilva** [comment]
Great, I think the solution indicated (in bold) for both cases should solve both problems.

**Comment by MichaelDBA** [comment]
Had to make a  whole bunch more changes than that! I went down the rabbit hole a bit.

@danieluisilva check now.

**Comment by danieluisilva** [comment]
:) Perfect

I've tested it and everything works fine.

Thanks

**Comment by MichaelDBA** [comment]
Thanks for your research into the problem, it helped.
