### ISSUE TITLE
Handle Special Characters in `tb.grantee` Column

### ISSUE THREAD

**Issue by alionar** [denishpatel/pg-clone-schema#108]
**Issue: Suggestion to Handle Special Characters in PostgreSQL Column `tb.grantee`**

**Description:**
I've identified an issue [in the code snippet](https://github.com/denishpatel/pg-clone-schema/blob/484e4ea06be96d060bf7ef54c50605ee3265aa02/clone_schema.sql#L2600) below:

```sql
quote_ident(dest_schema) || '.' || quote_ident(tb.table_name) || ' TO ' || string_agg(tb.grantee, ',') || ';' as tbl_dcl
```

The problem arises when the tb.grantee column contains special characters, causing errors in the SQL query execution. To address this issue, I suggest modifying the code as follows:
```sql
quote_ident(dest_schema) || '.' || quote_ident(tb.table_name) || ' TO ' || string_agg('"' || tb.grantee || '"', ',') || ';' as tbl_dcl
```

I've added double quotes around tb.grantee to escape any special characters within the grantee values, ensuring that the query works correctly in such cases.

**Steps to Reproduce:**
- Have a PostgreSQL column tb.grantee with a value containing special characters (ex: email format`test@example.com`)
- Execute the original code snippet.
- Observe the error due to unescaped special characters.

```Action: PRIVS: Tables  Diagnostics: line=PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1616 at EXECUTE. 42601. syntax error at or near "."```

**Proposed Change:**
Add double quotes around tb.grantee within the string_agg function to handle special characters.

**Benefits:**
This change will prevent errors caused by special characters in the tb.grantee column, making the code more robust and reliable. It will be relevant with [GCP's Cloud SQL IAM database authentication](https://cloud.google.com/sql/docs/postgres/authentication) that contains special character like `.` and `@` in pg username.

I'm open to feedback and further discussion on this suggestion. Please let me know your thoughts or if there are any concerns.

Thank you!

**Comment by MichaelDBA** [comment]
Fixed.  Also done for "ALTER TABLE ... OWNER TO" statements.
