### ISSUE TITLE
Bug - Setting default value per column in create table statement

### ISSUE THREAD

**Issue by nikleo-eng** [denishpatel/pg-clone-schema#110]
[clone_schema.sql](https://github.com/denishpatel/pg-clone-schema/blob/master/clone_schema.sql) 

In the _get_table_ddl_complex_ function the _coalesce_ operator, that prints the eventual default value associated with the column we are clonig for the DDL statement of the create table, is wrong; even if the column has not a default value, it prints _' DEFAULT '_ without value and in the case of a column not nullable the DDL statement generated is of type _'create table target_schema.table_x ( id_table_x numeric default not null ...'_ and this statement throws an error, because the form _default not null_ is not accepted by PostgreSQL

As is:
`coalesce(
              ' DEFAULT '
                || (
                  SELECT pg_catalog.pg_get_expr(d.adbin, d.adrelid)
                  FROM pg_catalog.pg_attrdef d
                  WHERE d.adrelid = pa.attrelid
                    AND d.adnum = pa.attnum
                    AND pa.atthasdef
                ),
              ''
            )`

To be:
`coalesce(
                (
                  SELECT ' DEFAULT ' || pg_catalog.pg_get_expr(d.adbin, d.adrelid)
                  FROM pg_catalog.pg_attrdef d
                  WHERE d.adrelid = pa.attrelid
                    AND d.adnum = pa.attnum
                    AND pa.atthasdef
                ),
              ''
            )`

**Comment by MichaelDBA** [comment]
@nikleo-eng I tried to duplicate your case and I could not.  Please provide an example where a DEFAULT is provided but with no value.

**Comment by MichaelDBA** [comment]
Looking at your solution a bit more I see that your proposed solution is actually erroneous because the SELECT becomes part of the final DDL!  Also, since you did not respond to my last question, I'm closing this issue.
