### ISSUE TITLE
Bug - The triggers have to be cloned only after the eventual tables rows cloning

### ISSUE THREAD

**Issue by nikleo-eng** [denishpatel/pg-clone-schema#111]
[clone_schema.sql](https://github.com/denishpatel/pg-clone-schema/blob/master/clone_schema.sql)

As done with the foreign keys, even the triggers have to be cloned only after the eventual tables rows cloning: otherwise during the cloning of the rows, the triggers, yet created, modify the inserted rows and so the result of the cloning procedure, at the end, not passes the comparing/equality tests

as is:
from line https://github.com/denishpatel/pg-clone-schema/blob/073922e2fffe5c65c4b948f244a7caaad51429bd/clone_schema.sql#L2463

to be:
to line https://github.com/denishpatel/pg-clone-schema/blob/073922e2fffe5c65c4b948f244a7caaad51429bd/clone_schema.sql#L3231

code affected:

> -- MV: Create Triggers
> 
>   -- MJV FIX: #38
>   -- EXECUTE 'SET search_path = ' || quote_ident(source_schema) ;
> 
>   -- Issue#61 FIX: use set_config for empty string
>   -- SET search_path = '';
>   SELECT set_config('search_path', '', false) into v_dummy;
> 
>   action := 'Triggers';
>   cnt := 0;
>   FOR arec IN
>     -- 2021-03-09 MJV FIX: #40 fixed sql to get the def using pg_get_triggerdef() sql
>     SELECT n.nspname, c.relname, t.tgname, p.proname, REPLACE(pg_get_triggerdef(t.oid), quote_ident(source_schema), > quote_ident(dest_schema)) || ';' AS trig_ddl
>     FROM pg_trigger t, pg_class c, pg_namespace n, pg_proc p
>     WHERE n.nspname = quote_ident(source_schema)
>       AND n.oid = c.relnamespace
>       AND c.relkind in ('r','p')
>       AND n.oid = p.pronamespace
>       AND c.oid = t.tgrelid
>       AND p.oid = t.tgfoid
>       ORDER BY c.relname, t.tgname
>   LOOP
>     BEGIN
>       cnt := cnt + 1;
>       IF bDDLOnly THEN
>         RAISE INFO '%', arec.trig_ddl;
>       ELSE
>         EXECUTE arec.trig_ddl;
>       END IF;
>
>    END;
>   END LOOP;
>   RAISE NOTICE '    TRIGGERS cloned: %', LPAD(cnt::text, 5, ' ');

**Comment by MichaelDBA** [comment]
@nikleo-eng I am not able to duplicate your issue, please provide a working example of a table with a trigger that is being executed during the cloning process.
