### ISSUE TITLE
Error with citext and array in the same table

### ISSUE THREAD

**Issue by ktowen** [denishpatel/pg-clone-schema#114]
I'm getting this error:
```
SQL Error [P0001]: ERROR: Version: 1.19  September 07, 2023  Action: Tables  Diagnostics: line=PL/pgSQL function clone_schema(text,text,cloneparms[]) line 733 at EXECUTE. 42601. syntax error at or near "ARRAY"

  Where: PL/pgSQL function clone_schema(text,text,cloneparms[]) line 2657 at RAISE
```
and I see it happening in a table with a `citext` and a `_varchar` column so I think it might be related. Both fields alone works well.
 
I'm able to reproduce it with this backup file in postgres 13.9 and `select clone_schema('my_schema', 'my_schema_1');`
[clone_test.zip](https://github.com/denishpatel/pg-clone-schema/files/13940179/clone_test.zip)

**Comment by MichaelDBA** [comment]
@ktowen please test with the latest build.

**Comment by ktowen** [comment]
It's working perfectly. Thanks @MichaelDBA for the quick response
