### ISSUE TITLE
Table permissions for public role invalidly assigned to non-existing "PUBLIC" role

### ISSUE THREAD

**Issue by hlampert** [denishpatel/pg-clone-schema#117]
There seems to be a  regression caused by the implementation of the issue 108, "FIX: enclose double-quote grantees with special characters" fix in the "PRIVS: tables" section.  When the public role has select rights on a table,  the code tries to grant SELECT to role "PUBLIC",   The double quotes around "PUBLIC" cause an error, as "PUBLIC" (all caps), does not match the actual role, which is "public" (all lower case).  This is not an issue when the role is written without double quotes, as all non-quoted identifiers are cast to lower-case by the query engine automatically.

Example error:

ERROR: Version: 1.22  January 24, 2024  Action: PRIVS: Tables  Diagnostics: line=SQL statement "GRANT SELECT ON TABLE datamart2023.rollover_specialist TO "edm_mdw_ro","PUBLIC","edm_ec2_run","edm_mdw_batch","edm_mdw_dbo","admin001","edm_mdw_rw";"
PL/pgSQL function clone_schema(text,text,cloneparms[]) line 2545 at EXECUTE. 42704. role "PUBLIC" does not exist

Code that probably causes this error:

      SELECT c.relkind, 'GRANT ' || tb.privilege_type || CASE WHEN c.relkind in ('r', 'p') THEN ' ON TABLE ' WHEN c.relkind in ('v', 'm')  THEN ' ON ' END ||
      -- Issue#78 FIX: handle case-sensitive names with quote_ident() on t.relname      
      -- Issue#108 FIX: enclose double-quote grantees with special characters
      -- quote_ident(dest_schema) || '.' || quote_ident(tb.table_name) || ' TO ' || string_agg(tb.grantee, ',') || ';' as tbl_dcl
      quote_ident(dest_schema) || '.' || quote_ident(tb.table_name) || ' TO ' || string_agg('"' || tb.grantee || '"', ',') || ';' as tbl_dcl

**Comment by MichaelDBA** [comment]
I was able to validate this bug, workin on it...

**Comment by MichaelDBA** [comment]
Fixed.  Please test with the latest build.

**Comment by hlampert** [comment]
This issue has been resolved.  Many thanks for the rapid response!
