### ISSUE TITLE
Syntax error search path

### ISSUE THREAD

**Issue by maxfornacon** [denishpatel/pg-clone-schema#119]
The error I receive when executing `select clone_schema('copied_schema', 'dest_schema_test', 'NODATA', 'DEBUG');`

```
NOTICE:         FKEYS cloned:    39
NOTICE:      TRIGGERS cloned:     0
ERROR:  Version: 1.24 January 28, 2024  Action: Triggers  Diagnostics: line=PL/pgSQL function clone_schema(text,text,cloneparms[]) line 2757 at EXECUTE. 42601. syntax error at or near "$"

CONTEXT:  PL/pgSQL function clone_schema(text,text,cloneparms[]) line 2781 at RAISE
```

In line 2757 the search_path is set to the old value:
`EXECUTE 'SET search_path = ' || src_path_old;`

I printed out the value with:
`RAISE NOTICE 'Restoring old search_path to:%', src_path_old;`

this led to this output:
`Restoring old search_path to:"\"$user"", public, extensions`

This is the output from the beginning of the script where the search_path variables are set:
```
NOTICE:  DEBUG: search_path="\$user", public, extensions
NOTICE:  DEBUG: src_path_old="\"$user"", public, extensions
NOTICE:  DEBUG: new search_path=copied_schema
```

My guess is that there is an issue with the `\`.

**Comment by MichaelDBA** [comment]
nice debugging work, thanks for the help...investigating...

**Comment by maxfornacon** [comment]
Setting the search path like this lets clone_schema() run smoothly. 

So is this a bug of supabase? It differs from the official Postgres documentation. If yes I might report an issue there.

**Comment by MichaelDBA** [comment]
Please post what PG Documentation you are referring to, plz.

**Comment by maxfornacon** [comment]
> Please post what PG Documentation you are referring to, plz.

https://www.postgresql.org/docs/15/ddl-schemas.html

**Comment by MichaelDBA** [comment]
OK, so report this as a bug to supabase then.  It is not the PG recommended way.

**Comment by maxfornacon** [comment]
Ok, let's see what they have to say about it.  I'll keep you updated on this.

**Comment by MichaelDBA** [comment]
I'm closing this issue, since it will not be fixed.
