### ISSUE TITLE
TSVector Columns lead to multiple create statements for the same table

### ISSUE THREAD

**Issue by luhagel** [denishpatel/pg-clone-schema#121]
Heya,
right now, the script throws when trying to copy a table with an autogenerated tsvector column, because it gets selected twice in the initial `DISTINCT ON` clause.

![Screenshot 2024-02-16 at 14 39 30](https://github.com/denishpatel/pg-clone-schema/assets/7240688/9c95df5f-daa1-4fa1-bde6-3da93429d619)

I'll try to fix this myself and contribute a patch, but I'm not sure my sql is at the level where it needs to be for that ^^

**Comment by MichaelDBA** [comment]
@luhagel , please provide a sample create table DDL statement that illustrates this problem.  Thanks in advance.

**Comment by luhagel** [comment]
So, it turns out that simply dropping the `co.is_generated = 'ALWAYS'` in line 9 of the snippet works for our use-case, but I'm not sure whether this creates any followup problem for other people

```sql
SELECT DISTINCT ON (c.relname, c.relpersistence, c.relispartition, c.relkind, co.data_type) c.relname, c.relpersistence, c.relispartition, c.relkind, co.data_type, co.udt_name, co.udt_schema, obj_description(c.oid), i.inhrelid, 
                    COALESCE(co.is_generated, ''), '"' || pg_catalog.pg_get_userbyid(c.relowner) || '"' as "Owner", CASE WHEN reltablespace = 0 THEN 'pg_default' ELSE ts.spcname END as tablespace                    
    FROM pg_class c
        JOIN pg_namespace n ON (n.oid = c.relnamespace
                AND n.nspname = quote_ident(source_schema)
                AND c.relkind IN ('r', 'p'))
        LEFT JOIN information_schema.columns co ON (co.table_schema = n.nspname
                AND co.table_name = c.relname
                AND (co.data_type = 'USER-DEFINED' OR co.is_generated = 'ALWAYS'))
        LEFT JOIN pg_inherits i ON (c.oid = i.inhrelid) 
        -- issue#99 added join
        LEFT JOIN pg_tablespace ts ON (c.reltablespace = ts.oid) 
    ORDER BY c.relkind DESC, c.relname
    ```

**Comment by MichaelDBA** [comment]
@luhagel, would still like to have a sample DDL create table statement to verify your problem with...

**Comment by luhagel** [comment]
Sorry, your reply only popped up after I hit submit on my reply :)

Here you go:

```sql
CREATE SCHEMA clone_repro
	CREATE TABLE contact (
		id uuid NOT NULL,
		email citext NOT NULL,
		searchable tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(translate(email, '@.-',  ' '), ''))) STORED
	)
```

**Comment by MichaelDBA** [comment]
Been looking at this for a few and I see a few places where this breaks stuff.  Also have to new logic to handle this complex identity column def...  Thanks for the report though, might take a while to fix it.  Give me a couple days to a couple weeks...

**Comment by MichaelDBA** [comment]
@luhagel, I have fixed this issue, which required a major rewrite though...  I am doing the regression testing now...  Should have it updated here in a couple days...

**Comment by luhagel** [comment]
@MichaelDBA oh wow, thank you so much for all your efforts!

**Comment by MichaelDBA** [comment]
@luhagel, Latest build is available now, try it out and let me know how it works...

**Comment by MichaelDBA** [comment]
Fixed even though no response to confirm yet.

**Comment by MichaelDBA** [comment]
@luhagel Currently, case-sensitive schemas are not supported at the present time.  A schema with hyphens in it is also a case-sensitive schema since it can only be created with double quotes around it.  I will add this to the readme.

**Comment by luhagel** [comment]
@MichaelDBA  Oh that's interesting, because the case-sensitive schema warning didn't trigger for me and as I wrote, two more `quote_indent(dest_schema)` wrappings caused everything to work flawlessly as far as i can tell.
