### ISSUE TITLE
Problem execution clone schema

### ISSUE THREAD

**Issue by mantoze** [denishpatel/pg-clone-schema#125]
Debug log:

NOTICE:  clone_schema version 2.0 February 20, 2024
NOTICE:  DEBUG: arguments={NODATA,DEBUG}
NOTICE:  DEBUG: arg=NODATA
NOTICE:  DEBUG: arg=DEBUG
NOTICE:  Linux: PostgreSQL 15.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
NOTICE:  DEBUG: search_path="$user", public
NOTICE:  DEBUG: src_path_old="$user", public
NOTICE:  DEBUG: new search_path=general_schema
NOTICE:  Section=Collations
NOTICE:    COLLATIONS cloned:     0
NOTICE:  Section=Domains
NOTICE:       DOMAINS cloned:     0
NOTICE:  Section=Types
NOTICE:         TYPES cloned:     2
NOTICE:  Section=Sequences
NOTICE:  DEBUG: CREATE SEQUENCE sample_clone.client_persons_id_seq;
NOTICE:  DEBUG: object=client_persons_id_seq  Sequence owner=sample_clone.client_persons.id  buffer=ALTER SEQUENCE sample_clone.client_persons_id_seq OWNED BY sample_clone.client_persons.id;
......................
NOTICE:     SEQUENCES cloned:    11
NOTICE:  Section=Tables
NOTICE:  DEBUG: search_path=general_schema
NOTICE:  DEBUG: setting search_path to empty string:
NOTICE:  DEBUG: TABLE START --> table=client_persons  bRelispart=f  relkind=r  bChild=f
NOTICE:  DEBUG: tabledef02:CREATE TABLE sample_clone.client_persons (LIKE general_schema.client_persons INCLUDING ALL)
NOTICE:  DEBUG: TABLE START --> table=clients  bRelispart=f  relkind=r  bChild=f
NOTICE:  DEBUG: Table (clients) has column(s) with user-defined types so using pg_get_tabledef() instead of CREATE TABLE LIKE construct.
NOTICE:  DEBUG: tabledef01a:CREATE  TABLE sample_clone.clients (
  id serial NOT NULL,
  active boolean NOT NULL DEFAULT true,
  type public.client_type NOT NULL,
  title character varying(200) NOT NULL,
  code character varying(20) NOT NULL DEFAULT ''::character varying,
  vat boolean NOT NULL DEFAULT true,
  vat_code_is_code boolean NOT NULL DEFAULT true,
  vat_code character varying(20) NOT NULL DEFAULT ''::character varying,
  address character varying(250) NOT NULL DEFAULT ''::character varying,
  email character varying(200) NOT NULL,
  phone character varying(50) NULL DEFAULT ''::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NULL,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_email_key UNIQUE (email)
) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS clients_active_idx ON sample_clone.clients USING btree (active) TABLESPACE pg_default;
CREATE UNIQUE INDEX clients_code_idx ON sample_clone.clients USING btree (code) WHERE ((code)::text <> ''::text) TABLESPACE pg_default;
CREATE UNIQUE INDEX clients_vat_code_idx ON sample_clone.clients USING btree (vat_code) WHERE ((vat_code)::text <> ''::text) TABLESPACE pg_default;

Query 1 ERROR: ERROR:  Version: 2.0 February 20, 2024  Action: Tables  Diagnostics: line=PL/pgSQL function clone_schema(text,text,cloneparms[]) line 797 at EXECUTE. 42601. syntax error at or near "TABLESPACE"

LastSQL=CREATE  TABLE sample_clone.clients (
  id serial NOT NULL,
  active boolean NOT NULL DEFAULT true,
  type public.client_type NOT NULL,
  title character varying(200) NOT NULL,
  code character varying(20) NOT NULL DEFAULT ''::character varying,
  vat boolean NOT NULL DEFAULT true,
  vat_code_is_code boolean NOT NULL DEFAULT true,
  vat_code character varying(20) NOT NULL DEFAULT ''::character varying,
  address character varying(250) NOT NULL DEFAULT ''::character varying,
  email character varying(200) NOT NULL,
  phone character varying(50) NULL DEFAULT ''::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NULL,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_email_key UNIQUE (email)
) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS clients_active_idx ON sample_clone.clients USING btree (active) TABLESPACE pg_default;
CREATE UNIQUE INDEX clients_code_idx ON sample_clone.clients USING btree (code) WHERE ((code)::text <> ''::text) TABLESPACE pg_default;
CREATE UNIQUE INDEX clients_vat_code_idx ON sample_clone.clients USING btree (vat_code) WHERE ((vat_code)::text <> ''::text) TABLESPACE pg_default;

CONTEXT:  PL/pgSQL function clone_schema(text,text,cloneparms[]) line 2880 at RAISE

**Comment by MichaelDBA** [comment]
@mantoze , Please run this command and show debug output:
`SELECT * FROM public.pg_get_tabledef('general_schema', 'clients', True, 'FKEYS_NONE');`

**Comment by mantoze** [comment]
I think problem is with custom type public.client_type. Yes???

Command output:

```
CREATE  TABLE general_schema.clients (
  id serial NOT NULL,
  active boolean NOT NULL DEFAULT true,
  type public.client_type NOT NULL,
  title character varying(200) NOT NULL,
  code character varying(20) NOT NULL DEFAULT ''::character varying,
  vat boolean NOT NULL DEFAULT true,
  vat_code_is_code boolean NOT NULL DEFAULT true,
  vat_code character varying(20) NOT NULL DEFAULT ''::character varying,
  address character varying(250) NOT NULL DEFAULT ''::character varying,
  email character varying(200) NOT NULL,
  phone character varying(50) NULL DEFAULT ''::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NULL,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_email_key UNIQUE (email)
) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS clients_active_idx ON general_schema.clients USING btree (active) TABLESPACE pg_default;
CREATE UNIQUE INDEX clients_code_idx ON general_schema.clients USING btree (code) WHERE ((code)::text <> ''::text) TABLESPACE pg_default;
CREATE UNIQUE INDEX clients_vat_code_idx ON general_schema.clients USING btree (vat_code) WHERE ((vat_code)::text <> ''::text) TABLESPACE pg_default;
```

**Comment by MichaelDBA** [comment]
@mantoze Your output is missing all the debug info.  The 3rd parameter must be set to True.  Please rerun and show the complete output here.

**Comment by MichaelDBA** [comment]
@mantoze Please test again with the latest build.  Think I fixed it.

**Comment by mantoze** [comment]
Yes, it's fixed. Thank you
