### ISSUE TITLE
Error when udt is not in the source or public schema

### ISSUE THREAD

**Issue by caparker** [denishpatel/pg-clone-schema#127]
When the user defined type is not in public or in the source schema I get a `type does not exist error` when inserting data

Code to reproduce
```sql
  DROP DATABASE IF EXISTS clone_testing;

  CREATE DATABASE clone_testing;
  \c clone_testing;

  -- load the clone_schema function
  \i clone_schema.sql

  CREATE SCHEMA other;
  SET search_path = other, public;
  -- create a type in that schema

  CREATE TYPE mytype AS ENUM (
   'a'
  , 'b'
  );

  CREATE SCHEMA sample;
  SET search_path = sample, public;

  -- use that type
  CREATE TABLE IF NOT EXISTS test_udts (
    mytype other.mytype
  );

  -- add some data
  INSERT INTO test_udts (mytype) VALUES ('a');

  -- this will work
  SELECT clone_schema('sample', 'cloned_sample');

  SELECT clone_schema('sample', 'cloned_sample_2', 'DATA');
```
And the error
```sql
ERROR:  Version: 2.2 March 05, 2024  Action: Copy Rows  SearchPath: sample, public  oldSP=sample, public  newSP=sample  Diagnostics: line=PL/pgSQL function clone_schema(text,text,cloneparms[]) line 2740 at EXECUTE. 42704. type "mytype" does not exist
It appears you have a USER-DEFINED column type mismatch.  Try running clone_schema with the FILECOPY option. 
LastSQL=INSERT INTO cloned_sample_2.test_udts (mytype) SELECT mytype::text::mytype FROM sample.test_udts;
CONTEXT:  PL/pgSQL function clone_schema(text,text,cloneparms[]) line 2905 at RAISE
```

I made a fix for it so I will make a pull request for that as well so you can check it out

**Comment by MichaelDBA** [comment]
This project does not support multiple, user-defined schemas for various types of objects referenced by the source schema.  It is geared to handle the simple case where extension objects are created in the public schema.  Also see my comments on the pull request regarding complications introduced to your choice of editors.

**Comment by caparker** [comment]
No worries, thanks for taking a look. Sorry about the diff, I sometimes forget that remove trailing whitespaces automatically. One aspect of that pull request you may want to keep is the addition of installing `ltree` at the top of the sampledb file. Cheers.

**Comment by MichaelDBA** [comment]
Check out sampledb.sql.  I had already put that ltree stuff in it at the end before your suggestion :).  Good thinking though...
