### ISSUE TITLE
Comparing this approach vs using pg tools?

### ISSUE THREAD

**Issue by mobleyc** [denishpatel/pg-clone-schema#134]
Hi I just discovered this project and was interested if you have any thoughts on pros and cons of this approach vs an approach like the following:

1. `pg_dump --schema <schema>`
2.  Script to rename schema name
3. `pg_restore --schema <schema>`

I tried searching for existing notes on this but didn't notice anything. Thanks.

**Comment by MichaelDBA** [comment]
You cannot do that.  Please read the documentation for pg_restore.  There is no dynamic changing of schemas.  This would only work with text output where you would do global changes.  This is by far the slowest and largest way to download and upload.  With binary formats, which is much faster, you would not be able to do the schema replacement.

https://www.postgresql.org/docs/current/app-pgrestore.html

**Comment by mobleyc** [comment]
Yep I'm not implying `pg_restore` would do the rename, as mentioned in (2). I was just asking about functional differences, thanks.

**Comment by efrazier** [comment]
I think the main thing is that pg-clone is really fast. We use it to make customer specific schema's that can evolve according to their needs. So running a copy from a baseline schema is part of their setup process. It runs fast enough that we do do that within a reasonable UI interaction time (websocket reporting on complete).  That then gives us a lot more options down the road if a customer grows, for example, into needing their own infrastructure.
