### ISSUE TITLE
Fail to clone schema if schema name starts with a digit

### ISSUE THREAD

**Issue by adam-hrb** [denishpatel/pg-clone-schema#140]
According to the [PG documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) the schema name that is a 'quoted identifier' can start with a number.

But clone_schema does not see such schemas, complains that 'source schema 123a does not exist!'

Here is a quick reproducer:

```
create schema "123a";

select public.clone_schema('123a', '123backup', 'DATA','VERBOSE');
```

it might be related to this check
```
  SELECT oid 
  FROM pg_namespace
  WHERE nspname = quote_ident('123a');
```

that potentially should be changed to
```
  SELECT oid 
  FROM pg_namespace
  WHERE quote_ident(nspname) = quote_ident('123a');
```
(and likely in other places)

If I am on the right path - I can create a pull request for that, just let me know.

**Comment by MichaelDBA** [comment]
Validated your continued problems, workin' on it...

**Comment by MichaelDBA** [comment]
Please provide the DDL for the shittimeentry table.

**Comment by MichaelDBA** [comment]
Try latest code to verify  get_insert_table_ddl() works fine now, and I did introduce a problem with not only views, but privileges as well.   Will work on that tomorrow...

**Comment by MichaelDBA** [comment]
please try with 2.12, not 2.11

**Comment by MichaelDBA** [comment]
please reply with this:
 \dv source_schema.*
 \dv target_schema.*

**Comment by MichaelDBA** [comment]
@adam-hrb, I think I'm finished making the final changes to handle special cases of schema names with funky chars and/or starting with numbers.  Please try the latest code to see if we can close this issue.

**Comment by MichaelDBA** [comment]
hmmm, i never tested going to a non-standard schema, only moving from one!  oh well, here we go again...

**Comment by MichaelDBA** [comment]
@adam-hrb Got it, try again with the latest code.

**Comment by MichaelDBA** [comment]
I'm closing this issue now, since you are satisfied.  Please add stuff to the other sequences issue so I can validate your problems.
