### ISSUE TITLE
The procedure updates source schema (creates obj_type and perm_type)

### ISSUE THREAD

**Issue by adam-hrb** [denishpatel/pg-clone-schema#141]
Not sure if that is really a bug or a feature, but the procedure creates two types: obj_type and perm_type in the source schema.

Initially this was pretty confusing and difficult to pinpoint for us, as we compared the object count in source and target schema and it was failing only on the first run.
Is that necessary to create these types in source schema? Wouldn't it be better to create them in public schema, with the rest of the clone_schema code?

```
  lastsql = 'SET search_path = ' || quote_ident(source_schema) ;
  EXECUTE lastsql;
.....
  IF cnt = 0 THEN
    CREATE TYPE obj_type AS ENUM ('TABLE','VIEW','COLUMN','SEQUENCE','FUNCTION','SCHEMA','DATABASE');
  END IF;
  IF cnt2 = 0 THEN
    CREATE TYPE perm_type AS ENUM ('SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER','USAGE','CREATE','EXECUTE','CONNECT','TEMPORARY');
  END IF;
```

**Comment by MichaelDBA** [comment]
Nice catch!  Yeah, that was an unintended side-effect.  Try the latest code to verify they are not created in source schema and not propagated to the  target schema.
