### ISSUE TITLE
Triggers that reference functions in public schema are not cloned

### ISSUE THREAD

**Issue by rafaelfassi** [denishpatel/pg-clone-schema#147]
Thanks for the amazing project, it's very useful!

I just just realized that triggers that call functions on the public schema are not cloned by the script, but the project's description states the cloned schemas can reference objects defined on public:
> _This project does not support that at the present time. It only supports 3 schemas basically: the source schema, the target schema, and objects defined in the public schema referenced by those user-defined schemas._

The problem seems to be in the following query that gets the triggers:

```sql
SELECT
	n.nspname,
	c.relname,
	t.tgname,
	p.proname,
	REPLACE(pg_get_triggerdef(t.oid), quote_ident(source_schema), quote_ident(dest_schema)) || ';' AS trig_ddl
FROM pg_trigger t, pg_class c, pg_namespace n, pg_proc p
WHERE n.nspname = source_schema
      AND n.oid = c.relnamespace
      AND c.relkind in ('r','p')
      AND n.oid = p.pronamespace
      AND c.oid = t.tgrelid
      AND p.oid = t.tgfoid
ORDER BY c.relname, t.tgname
```

I think the condition `AND n.oid = p.pronamespace` can be removed as that only restricts the function to be in `source_schema`.

**Comment by MichaelDBA** [comment]
@rafaelfassi Nice catch!  I have validated the problem and am working on it...

**Comment by rafaelfassi** [comment]
@MichaelDBA Many thanks for the fix.
It's working like a charm now.
