### ISSUE TITLE
clone_schema with DATA fails when table column name is "desc"

### ISSUE THREAD

**Issue by drleon** [denishpatel/pg-clone-schema#149]
I have a table column: "desc" text. clone_schema with DATA fails with:

query failed: select clone_schema('init_v1', 'bolo_v1', 'DATA','VERBOSE');
error: error: Version: 2.17 December 7, 2024  Action: Copy Rows  CurrentSP: "$user", public  oldSP="$user", public  newSP=init_v1  Diagnostics: line=PL/pgSQL function clone_schema(text,text,cloneparms[]) line 3015 at EXECUTE. 42601. syntax error at or near "desc"

**Comment by MichaelDBA** [comment]
A workaround is to use the FILECOPY option when copying data:
SELECT * from clone_schema('sourceschema','targetschema', 'DATA','FILECOPY','VERBOSE');

**Comment by MichaelDBA** [comment]
@drleon Try the latest code now...

**Comment by drleon** [comment]
Hello,

Thx for a quick replay. It still fails on my side with:

query failed: select clone_schema('init_v1', 'bolo_v1', 'DATA','VERBOSE');
error: error: Version: 2.18 December 18, 2024  Action: Copy Rows  CurrentSP: "$user", public  oldSP="$user", public  newSP=init_v1  Diagnostics: line=PL/pgSQL function clone_schema(text,text,cloneparms[]) line 3015 at EXECUTE. 42601. syntax error at or near "desc"

**Comment by MichaelDBA** [comment]
Please try again, but replace VERBOSE with DEBUGEXEC

**Comment by MichaelDBA** [comment]
@drleon Get the latest code and try again, please...

**Comment by drleon** [comment]
Works fine now. No errors. schema_object_counts.sql returns the same numbers for the origin and the clone. Thx.
