### ISSUE TITLE
Error cloning permission - type "perm_type" does not exist

### ISSUE THREAD

**Issue by EspadaV8** [denishpatel/pg-clone-schema#16]
Just found that you've been managing this after we just upgraded from 9.6 to 11, but when running the latest master version we're getting the following error

```
ERROR:  Action: PRIVS: Schema  Diagnostics: 42704. type "perm_type" does not exist . .  PL/pgSQL function clone_schema(text,text,boolean) line 627 at GET STACKED DIAGNOSTICS
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean) line 629 at RAISE
STATEMENT:  select clone_schema('test_tenant', 'test_demo_3', false);
```

(I've removed the 4th parameter from our version of the function and just set it to `True` for now).

I think this is because there aren't any permissions getting returned, although I'm not exactly sure how to test this.

**Comment by MichaelDBA** [comment]
If you install pg_permissions extension (https://github.com/cybertec-postgresql/pg_permission), that will fix it.  In the meantime, I am working on using SQL to get permissions without the usage of that extension.

**Comment by EspadaV8** [comment]
Ah, thanks. Unfortunately we're using AWS RDS so we won't be able to install that extension. For now I think we can just remove the permission parts (they weren't in the function before so I don't think we'll miss them :smile:)

**Comment by MichaelDBA** [comment]
OK, I will make it a priority to get this fixed, probably today, since this is a showstopper for RDS.

**Comment by MichaelDBA** [comment]
Just  create these 2 TYPE definitions and then it should work:

```
CREATE TYPE perm_type AS ENUM (
   'SELECT',
   'INSERT',
   'UPDATE',
   'DELETE',
   'TRUNCATE',
   'REFERENCES',
   'TRIGGER',
   'USAGE',
   'CREATE',
   'EXECUTE',
   'CONNECT',
   'TEMPORARY'
);

CREATE TYPE obj_type AS ENUM (
   'TABLE',
   'VIEW',
   'COLUMN',
   'SEQUENCE',
   'FUNCTION',
   'SCHEMA',
   'DATABASE'
);

```

**Comment by MichaelDBA** [comment]
I have integrated the user types into clone_schema, so no additional extension or types need to be added.

**Comment by EspadaV8** [comment]
Great, thank you 🙂

**Comment by denishpatel** [comment]
thanks @MichaelDBA !
