### ISSUE TITLE
Issue with multiple ROLEs assigning permissions

### ISSUE THREAD

**Issue by denishpatel** [denishpatel/pg-clone-schema#18]
If you provide following two permission on sampledb, the clone schema will fail

ALTER DEFAULT PRIVILEGES FOR ROLE mydb_owner IN SCHEMA sample GRANT ALL ON SEQUENCES  TO mydb_owner;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA sample GRANT ALL ON SEQUENCES  TO mydb_owner;

**Comment by MichaelDBA** [comment]
ha, let me try!

**Comment by denishpatel** [comment]
oops! my bad. it should be GRANT, not REVOKE

**Comment by MichaelDBA** [comment]
Fixed the problem where multiple grantors are associated with the same grantee and privs.  Required rewrite of the DEFAULT PRIVILEGES section.  This is now pushed to main branch.
