### ISSUE TITLE
Malware in the cloning script  - DO NOT USE THIS SCRIPT

### ISSUE THREAD

**Issue by cuvialabs** [denishpatel/pg-clone-schema#32]
i used this script to copy a schema on heroko.    It immediately generated thousands of randomly named function with the copied schema.   It also attempted to make OS calls on my local machine.    DO NOT USE THIS SCRIPT.

**Comment by denishpatel** [comment]
@MichaelDBA  can you check ?

Thanks for reporting @cuvialabs

**Comment by denishpatel** [comment]
@cuvialabs if I have to make educational guess here.. it’s most likely heroku functions which you don’t know ! I will test again to make sure there is no malware and thanks for repy

**Comment by denishpatel** [comment]
@EspadaV8 @leshik @fsateler do you guys experience same issue reported?

**Comment by EspadaV8** [comment]
I haven't updated the copy of the script we use, but no, I have not see any kind of malware or dodgy behaviour. We have been using the script long before this repo was created

**Comment by EspadaV8** [comment]
@cuvialabs it is probably best if you post the output you are seeing so we can see what's actually happening

**Comment by cuvialabs** [comment]
I would,  but when I ran it,  it shut down my instance and I got a 'too many connections' from heroku for about 15 minutes.   But when I finally did get access,  all the functions were gone,   so I guess it rolled back the state changes.    As I mentioned,  it repeatedly attempted to make OS calls on my local machine.   I use Navicat as a sql modler and it kept popping up a dialog that said "OS call failed".     I would guess that it could be a heroku issue,  except for the OS calls.

**Comment by EspadaV8** [comment]
If you're running it on a remote DB and it is navicat throwing the errors it won't be the script trying to hack your computer, it'll be navicat failing at something. Can you try using pgsql instead, or something other than navicat. As far as I am aware there is no way to hack a local computer when running SQL on a remote server.

**Comment by leshik** [comment]
@denishpatel I'm using this script every day, multiple times per day, for more than a year now. DBs are AWS RDS instances of different sizes. I've never seen any of the issues described.

The worst thing I witnessed is when new records were added to a table on the source after its sequences have been already copied, but the table data is not - then errors on inserts are generated and sequences need to be advanced manually on target. But that's unrelated to this issue.

**Comment by fsateler** [comment]
I have not seen such behavior (although I use a locally copied version).

**Comment by cuvialabs** [comment]
Is there something in the script that creates functions?

**Comment by MichaelDBA** [comment]
I have reviewed the code in clone_schema.sql and there is no malware.  It does create schema functions if they are present in the source schema.  So if your source schema functions are corrupted so would your target schema functions be corrupted.

Leaving this open for a few more days until issue feedback seems complete.

**Comment by denishpatel** [comment]
thanks. I tested and it don't see any malware too.

**Comment by denishpatel** [comment]
@leshik please create new issue regarding sequence problem. thanks!

**Comment by MichaelDBA** [comment]
Closing this since there is no malware in this simple SQL script.  My bet is that your source was corrupted so when you copied over to the target using this tool, the corruption became evident.

**Comment by cuvialabs** [comment]
I could see the script creating 7000+ functions with random names before Heroku killed it.  I reviewed it looking for the random() function and found nothing either.   What’s stranger is,  I cut and pasted the script from from GitHub.   So I suspect it’s a reation to something in the Heroku environment.   But that’s some pretty strange behavior,   you should not dismiss this.

**Comment by MichaelDBA** [comment]
This script only gets its info from the PostgreSQL system tables.  The corruption lies elsewhere.
