### ISSUE TITLE
Type <some_type> does not exist

### ISSUE THREAD

**Issue by gabrielpiassetta** [denishpatel/pg-clone-schema#34]
I'm getting this error while running the clone_schema during the clone functions flow.

```
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 484 at EXECUTE. 42704. type "some_type" does not exist
```

when the source function uses the type in a `declare` statement. like:

```
DECLARE
    my_var some_type;
BEGIN
```

I realized that we clear the source_path before cloning the functions in:

```
-- Create functions
  action := 'Functions';
  cnt := 0;
  SET search_path = '';
```

I could solve the issue, changing the `SET search_path = '';` line to `EXECUTE 'SET search_path = ' || src_path_old;`

However, I'm thinking about why clone_schema clears the initial `search_path` that is the `source_schema` to be an empty one. Meaning that we should have the types on the public schema, which I think isn't the purpose of the cloning function.

What are your thoughts about this solution?

I can submit a PR for any of both solutions if you agree.

**Comment by MichaelDBA** [comment]
I disagree with types being defined on the public schema.  the Ideal is for all user objects to be in the same schema.  The only thing that should be in the public schema are extensions in my opinion.

Thanks Gabriel for your fix recommendation.  It was the correct move.  This is updated in master branch.

**Comment by gabrielpiassetta** [comment]
Hi Michael, I'm not facing another issue, related to that.

```
ERROR:  Action: PRIVS: Functions  Diagnostics: line=SQL statement "GRANT EXECUTE ON FUNCTION clone_schema_test_b.__crud_attributes(**clone_schema_test_b.crud_ops**,jsonb,jsonb,jsonb,jsonb) TO "pg_monitor";"
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 729 at EXECUTE. 42883. function clone_schema_test_b.__crud_attributes(clone_schema_test_b.crud_ops, jsonb, jsonb, jsonb, jsonb) does not exist
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean) line 773 at RAISE
```

cause the sql that created this function is actually:

```
CREATE OR REPLACE FUNCTION clone_schema_test_b.__crud_attributes(**crud_op crud_ops**, data jsonb, filtering jsonb DEFAULT NULL::jsonb, sorting jsonb DEFAULT NULL::jsonb, flags jsonb DEFAULT NULL::jsonb)
.
.
.
```

to help to debug it, creating the functions using the `src_path_old` as the search_path doesn't cause this error.

**Comment by MichaelDBA** [comment]
Hi Gabriel, would you please create that as another issue so we can track these bugs better?

**Comment by MichaelDBA** [comment]
I have reopened this issue until you create the new one.

**Comment by MichaelDBA** [comment]
Closing this since new issue opened for last problem noted in this issue.
