### ISSUE TITLE
Error on referencing source_schema on the trigger function

### ISSUE THREAD

**Issue by gabrielpiassetta** [denishpatel/pg-clone-schema#38]
Im facing the following issue when cloning the schema.

![IMG_20210308_141244](https://user-images.githubusercontent.com/1233356/110355804-6363fe00-8018-11eb-99ed-389326d92347.jpg)

The trigger function shouldn't be the one from the dest schema?

This is coming from this SQL

```
CREATE TRIGGER modify_after_delete_dimension_modalities AFTER DELETE ON dest_schema.dimension_modalities FOR EACH STATEMENT EXECUTE FUNCTION modify_dimension_modalities();
```

**Comment by MichaelDBA** [comment]
looking at it now...

**Comment by MichaelDBA** [comment]
Fixed, had to add replace statement and set search_path = '';
