### ISSUE TITLE
Schema hard coded in view

### ISSUE THREAD

**Issue by yaakovfeldman** [denishpatel/pg-clone-schema#43]
Thank you very much for this script.

My views all contain hard coded schema references to the schema that contains them. E.g. schema1 contains a view that references schema1.table1 and schema2 contains a view that references schema2.table1.

These references are not updated in the cloned schema. Views in the cloned schema still point to the tables in the original schema.

Is there any way to update these references? Or is my issue due to non colloquial use of postgres?

I have attempted to change the script to run REPLACE on the view definition as it is cloned but my changes seem to have no effect (probably due to my lack of experience with plpgsql).

**Comment by MichaelDBA** [comment]
Fixed
