### ISSUE TITLE
Problem when table name contains schema name

### ISSUE THREAD

**Issue by lorinkoz** [denishpatel/pg-clone-schema#44]
Hi there!

Thanks for maintaining this very useful repo!

I'm having a problem when cloning a schema that contains one table whose name includes the schema name, for instance `some_schema.table_with_some_schema_in_the_name`.

One of the referenced code chunks might be the culprit:

https://github.com/denishpatel/pg-clone-schema/blob/6b9b31bbe3e439e5a2c7f55c4275833c38b6e419/clone_schema.sql#L544

https://github.com/denishpatel/pg-clone-schema/blob/6b9b31bbe3e439e5a2c7f55c4275833c38b6e419/clone_schema.sql#L672

Happy to submit a PR. Will enclosing the arguments in `quote_ident` solve the problem?

**Comment by lorinkoz** [comment]
For context, this is the error I am getting:

```
CommandError: Action: Tables  Diagnostics: line=sentencia SQL: «ALTER TABLE reference.waffle_sample ALTER COLUMN id SET DEFAULT nextval('reference.waffle_reference_id_seq'::regclass)»
función PL/pgSQL clone_schema(text,text,boolean,boolean) en la línea 375 en EXECUTE. 42P01. no existe la relación «reference.waffle_reference_id_seq»
CONTEXT:  función PL/pgSQL clone_schema(text,text,boolean,boolean) en la línea 769 en RAISE
```

Schema name is `sample` and there is a table called `waffle_sample`. I was trying to clone `sample` to `reference`.

**Comment by lorinkoz** [comment]
In order to reproduce the problem, just create a table that contains the same name of the schema, then try to clone that schema. For instance, if the schema is called `whatever` you can create a table called `whatever` and see what happens.

**Comment by MichaelDBA** [comment]
Yes I have a source table named sampletable in the sample schema. And it exports fine to sample2 schema.
sample.sampletable

**Comment by MichaelDBA** [comment]
Please provide the example you said you would provide if I cannot reproduce the error.

**Comment by lorinkoz** [comment]
I am unable to work on this right now. Will close and reopen when I can confirm. Thanks.
