### ISSUE TITLE
Any roadmap for including automated tests?

### ISSUE THREAD

**Issue by lorinkoz** [denishpatel/pg-clone-schema#45]
Hi!

Is there any roadmap or plan to include automated tests on this repo, so that the correctness of the procedure can be asserted programatically? I'll be more than happy to help with the initial scaffolding and tests if we can agree on a way to do this.

**Comment by MichaelDBA** [comment]
PgAdmin4 has a nice schema diff tool.  I think that works for now.  Also, see the **schema_object_counts.sql** file above.  It does a nice object count comparison.

**Comment by lorinkoz** [comment]
Thanks @MichaelDBA. I was concerned about https://github.com/denishpatel/pg-clone-schema/issues/44 and was wondering if there was an automated way to make sure this doesn't happen again after fixed.

**Comment by MichaelDBA** [comment]
#44 is still not fixed. waiting on user input

**Comment by MichaelDBA** [comment]
The main regression tool for this project is using the sampledb.sql file for testing.  It creates a sample database with a sample schema that contains a bunch of different kinds of objects.  We do regression testing by cloning that schema.
