### ISSUE TITLE
reference to non existent field in PRIVS section

### ISSUE THREAD

**Issue by dpmillerau** [denishpatel/pg-clone-schema#46]
There are references to nonexistent fields in the PRIVS section see my commit for change. One is in a commented out debug

https://github.com/dpmillerau/pg-clone-schema/commit/f32488baaaee9ac3dc839f954da227dba4f52d64#diff-f2c8f6cbb117540fc01e34353d4ab0c70d7f0a9b98efdb77bfeaa7ebaafbabdb

**Comment by MichaelDBA** [comment]
Thanks, Fixed.
