### ISSUE TITLE
Coding style (low priority)

### ISSUE THREAD

**Issue by guignonv** [denishpatel/pg-clone-schema#53]
While working on the clone_schema.sql script (cf. my recent pull requests! ;) ), I noticed not all the code follows the same coding style (and sometimes no style at all! :) ).
It's not a big deal but it would be nice to follow a same style for the whole file.
One can find many different coding styles for SQL on the net. I am not attached to a specific one but I just it would be nice to select one and use it for clarity (reading) and code sharing.
If I had to choose, I would go for (as a suggestion):
- capitalize reserved words
- lowercase for object names (schema, tables, columns,...) and functions
- no space between functions and parenthesis
- no more than 1 space between words
- main keywords on new line and vertically aligned by level
- two spaces indentation
- indent next line when it is a sub-part of the line above
- lines should not exceed 80 characters as much as possible
- comments above the related code line
...

It would look like this for instance:
```
SELECT
  con.conname AS constraint_name,
  con.contype AS constraint_type,
  CASE
    -- primary key constraint
    WHEN con.contype = 'p' THEN 1
    -- unique constraint
    WHEN con.contype = 'u' THEN 2
    -- foreign key constraint
    WHEN con.contype = 'f' THEN 3
    WHEN con.contype = 'c' THEN 4
    ELSE 5
  END AS type_rank,
  pg_get_constraintdef(con.oid) AS constraint_definition
FROM pg_catalog.pg_constraint con
  JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
  JOIN pg_catalog.pg_namespace nsp ON nsp.oid = connamespace
WHERE nsp.nspname = in_schema
  AND rel.relname = in_table
ORDER BY type_rank
```
I could work on that once all my PR are accepted. ;)

**Comment by denishpatel** [comment]
@guignonv All your PRs are approved. Can you work on it now?

**Comment by guignonv** [comment]
I've started the work but it's too much for me right now. See PR #68.
If someone wants to continue, feel free!
As I said in the PR, I gave a try to pgFormatter (https://github.com/darold/pgFormatter) but it did not work as expected. I also try to find other automated tools without success.

**Comment by MichaelDBA** [comment]
Beginning regression testing on the changes before approving the merge of the pulled request.

**Comment by MichaelDBA** [comment]
Errors introduced. Merge rejected. Pull Request Closed. 

Aliases in SQL statements are double-quoted. This breaks code references to them in lowercase.

**Comment by MichaelDBA** [comment]
Also note that clone schema was updated subsequent to this for issue#69. So refactor from the latest.

**Comment by MichaelDBA** [comment]
formatted SQL per pgFormatter tool
