### ISSUE TITLE
Missing: Foreign Tables?

### ISSUE THREAD

**Issue by MichaelDBA** [denishpatel/pg-clone-schema#6]
I think the information_schema does not list foreign tables.  I may be wrong, but need to investigate...

**Comment by MichaelDBA** [comment]
Back to original subject of this issue: Foreign Tables...  My thinking was misplaced.  Cloning a schema is not really related to what schema is referenced in another database through a foreign table definition.

**Comment by denishpatel** [comment]
@MichaelDBA  I like your approach to use pg_dump to export all schemas including foreign schema

it should be optional though.

**Comment by MichaelDBA** [comment]
Will not address at current time.  Limitation of foreign tables will be documented in readme.
