### ISSUE TITLE
Add comments 

### ISSUE THREAD

**Issue by MichaelDBA** [denishpatel/pg-clone-schema#62]
Currently, comments on most objects are not captured and cloned.  Thanks to @guignonv for providing the code to do it for indexes only, which is implemented.  Please add comments for other objects as well.  And note them here as they are done and integrated into the master.

**Comment by MichaelDBA** [comment]
Done!  Re-arranged how we gather comments in one place.   Removed it from 2 places:
1. table section
2. separate section just for indexes

**Comment by denishpatel** [comment]
Thanks @MichaelDBA !
