### ISSUE TITLE
Clone tables does not include identity secuence values

### ISSUE THREAD

**Issue by gunnarvelle** [denishpatel/pg-clone-schema#63]
When cloning schemas where primary keys in tables are defined as identity columns, postgres automatically creates new sequences for the keys, because of the 'INCLUDING ALL' parameter. But the sequences are not set to the same value as in the original schema, but is reset to the starting value. Any attempts to insert new data into the tables fails because the sequence starts at 1.
The script should update the corresponding sequences with the correct value from the sequence in the source schema.

**Comment by gunnarvelle** [comment]
I was a bit to quick. Postgres recreates the sequences automatically, so you end up getting duplicates. Will look into this closer.

**Comment by MichaelDBA** [comment]
Now its fixed and passes regression testing.
