### ISSUE TITLE
Cloning comments doesn't work when they contain apostrophes

### ISSUE THREAD

**Issue by callum-p** [denishpatel/pg-clone-schema#74]
Policies 1 and 2 actions were breaking for me doing clones due to the quoting around descriptions.

I believe it should do something like this `' IS ' || quote_literal(d.description) || ';'` instead of `' IS ''' || d.description || ''';'`.

I was going to put up a PR but my IDE got rid of all the extra spaces at the end of the lines and it was a bit of a PITA fix.

**Comment by MichaelDBA** [comment]
@callum-p I was not able to duplicate the problem.  Please provide a sample DDL of a policy that does not convert successfully.

**Comment by MichaelDBA** [comment]
Fixed.
