### ISSUE TITLE
Avoid errors by quote problems

### ISSUE THREAD

**Issue by nocyamribeiro** [denishpatel/pg-clone-schema#78]
I had three consecutive errors related to the quote problem. Here they are:

1.
 ```
SQL Error [P0001]: ERROR: Action: Tables  Diagnostics: line=SQL statement "ALTER TABLE teste_clone."CUBE_6c1b118be1df454e8b1770822d5cbe45_FACT" ALTER COLUMN FACT_ORDER SET DEFAULT nextval('teste_clone."CUBE_6c1b118be1df454e8b1770822d5cbe45_FACT_FACT_ORDER_seq"'::regclass)"
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 688 at EXECUTE. 42703. column "fact_order" of relation "CUBE_6c1b118be1df454e8b1770822d5cbe45_FACT" does not exist
  Where: PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1584 at RAISE
```

2. 
```
SQL Error [P0001]: ERROR: Action: PRIVS: Sequences  Diagnostics: line=SQL statement "GRANT SELECT ON teste_clone.CUBE_72a2ff79600040f488b43fe7887a6da7_FACT_FACT_ORDER_seq TO "user";"
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1488 at EXECUTE. 42P01. relation "teste_clone.cube_72a2ff79600040f488b43fe7887a6da7_fact_fact_order_seq" does not exist
  Where: PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1584 at RAISE
```
  
3. 
```
SQL Error [P0001]: ERROR: Action: PRIVS: Tables  Diagnostics: line=SQL statement "GRANT DELETE ON TABLE teste_clone.CUBE_6c1b118be1df454e8b1770822d5cbe45_FACT TO user;"
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1563 at EXECUTE. 42P01. relation "teste_clone.cube_6c1b118be1df454e8b1770822d5cbe45_fact" does not exist
  Where: PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1584 at RAISE
```

**Comment by MichaelDBA** [comment]
Thanks for the valid issue.  The problem is a bit bigger than just using the quote_ident() function in a few places.  Apparently, clone_schema does not handle "case-sensitive" object names very well.  Since I have found multiple other areas that need to be fixed as well, I will not be using your pull request since it only partially addresses the problem, but thanks for the effort!  You are on the right path.  I'm working on this now...

**Comment by nocyamribeiro** [comment]
@MichaelDBA I really appreciate your attention and how fast you solved our problem. I just tested the new clone_schema.sql code and everything ran well

**Comment by MichaelDBA** [comment]
Thank you, @nocyamribeiro, for identifying the problem and providing the correct solution for it using the quote_ident() function.

**Comment by nocyamribeiro** [comment]
Hi @MichaelDBA,  I've tested the new code in another database and the followed error shows up:

```
SQL Error [P0001]: ERROR: Action: PRIVS: Tables  Diagnostics: line=SQL statement "INSERT INTO teste_clone.attribute SELECT * FROM bi_test1.attribute;"
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1655 at EXECUTE. 23503. insert or update on table "attribute" violates foreign key constraint "fkc7aa9ceaa3d6f3"
  Where: PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1687 at RAISE
```

Before the last update, this error didn't happen in this database.

I'm trying to discover what broken the implementation. Do you have a suggestion?

**Comment by MichaelDBA** [comment]
hmmm, me thinks it was not implementing foreign keys TIL after we did the row copies.  Let me fix this if that is the problem.  Since I do no "ordering" for inserts when copying data.  We must defer creating the FKeys until after the copy is done.

**Comment by MichaelDBA** [comment]
@nocyamribeiro 
Yep, that sure was the problem.  It is now fixed again.  Please try again.

**Comment by nocyamribeiro** [comment]
Hi @MichaelDBA I've tested in both databases that I had this problem and script ran ok. I'll close the issue and if some problem happens I'll keep you posted. Thank you again!
