### ISSUE TITLE
Index duplication error

### ISSUE THREAD

**Issue by MichaelDBA** [denishpatel/pg-clone-schema#83]
If a table has CONSTRAINT Defs, it may have duplicate CREATE INDEX statements added to it.

**Comment by MichaelDBA** [comment]
Fixed. Do not add CREATE INDEX statements if CONSTRAINT Defs already defined for them.

**Comment by Brent-Wood** [comment]
Made much more progress before failing, tables processed and on to materialised views, but failed as:

NOTICE:   Populated cloned table, trawl_dev2.t_station                  Rows Copied: 60640
ERROR:  Action: Copy Rows  Diagnostics: line=COPY t_stratum_defn, line 1: "334,0042,2007,2008,tan0709,POLYGON((185.77855 -43.33333\,185.77855 -43.3316\,185.77849 -43.33151\,18..."
SQL statement "COPY trawl_dev2.t_stratum_defn  FROM '/tmp/cloneschema.tmp' (DELIMITER ',', NULL '\N', FORMAT CSV);"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1657 at EXECUTE. 22P04. extra data after last expected column
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1719 at RAISE

I figure that somewhere the dump file has an extra un-escaped comma. Likely to relate to a Postgis column. I'll look into it & get back...

**Comment by Brent-Wood** [comment]
With this error:

ERROR:  Action: Copy Rows  Diagnostics: line=COPY t_stratum_defn, line 19: "545,1,\N,\N,lhr1001\,IQCH,\N,0106000020E61000000100000001030000000200000098060000B6B4CE57D5C16540B2B..."
SQL statement "COPY trawl_dev2.t_stratum_defn  FROM '/tmp/cloneschema.tmp' (DELIMITER ',', NULL '\N', FORMAT CSV);"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1657 at EXECUTE. 22P04. extra data after last expected column
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1719 at RAISE

I'm looking at the supposed data file being copied into the table ('/tmp/cloneschema.tmp') and this only ever has one row of text, which does not match the columns or content. I can't find the error in the row being inserted as the file seems to be overwritten before the clone_schema() function exits after the error.

**Comment by MichaelDBA** [comment]
Please dont add to this closed issue unless its related to the duplicate index problem.  I will create an issue to track the copy problem noted above.
