### ISSUE TITLE
COPY Error for PostGIS column table

### ISSUE THREAD

**Issue by MichaelDBA** [denishpatel/pg-clone-schema#84]
@Brent-Wood :
With this error:

ERROR: Action: Copy Rows Diagnostics: line=COPY t_stratum_defn, line 19: "545,1,\N,\N,lhr1001,IQCH,\N,0106000020E61000000100000001030000000200000098060000B6B4CE57D5C16540B2B..."
SQL statement "COPY trawl_dev2.t_stratum_defn FROM '/tmp/cloneschema.tmp' (DELIMITER ',', NULL '\N', FORMAT CSV);"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1657 at EXECUTE. 22P04. extra data after last expected column
CONTEXT: PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1719 at RAISE

I'm looking at the supposed data file being copied into the table ('/tmp/cloneschema.tmp') and this only ever has one row of text, which does not match the columns or content. I can't find the error in the row being inserted as the file seems to be overwritten before the clone_schema() function exits after the error.

**Comment by MichaelDBA** [comment]
First of all, the temp file is generated on the DB server, not locally on your client machine. It should still be there since the same file is used over and over again.  Can you get access to that?

**Comment by Brent-Wood** [comment]
That makes sense. An obvious oversight on my part, my apologies. Our IT team do not allow our DBA's to have system logins on the database server, so I cannot access the file myself, but I can ask for them to provide me with a copy. 

Thanks...

**Comment by MichaelDBA** [comment]
or perhaps create a small sample table that can demonstrate this problem and post here.

**Comment by MichaelDBA** [comment]
I am not able to duplicate the problem.  Please post a snippet that illustrates your problem.

**Comment by MichaelDBA** [comment]
Please respond back to this issue or I will close it soon.

**Comment by MichaelDBA** [comment]
Cannot duplicate the problem and issue creator is not responsive anymore.
