### ISSUE TITLE
operator does not exist: text[] || name

### ISSUE THREAD

**Issue by furlongce** [denishpatel/pg-clone-schema#85]
I'm trying to run this utility and I'm consistently running into the following error if I try to create a schema that doesn't already exist:

`[2022-09-27 10:12:34] [P0001] ERROR: Action: Tables  Diagnostics: line=PL/pgSQL function public.get_table_ddl(character varying,character varying,boolean) line 196 at assignment
[2022-09-27 10:12:34] SQL statement "SELECT *              FROM public.get_table_ddl(quote_ident(source_schema), tblname, False)"
[2022-09-27 10:12:34] PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 502 at SQL statement. 42883. operator does not exist: text[] || name
[2022-09-27 10:12:34] Where: PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1719 at RAISE`

When I try to run it w/ an existing schema, nothing happens at all, but I don't get an error.

select clone_schema('deid', 'here2', false, true, true);
select clone_schema('deid', 'here2', true, false, true);

This is running with PostgreSQL 13.8.

**Comment by furlongce** [comment]
I've been trying to troubleshooting, and it seems to be related to having a primary key defined.

If I create a new table, it works:

`create table deid.testing
(
    column_1 integer not null
);`

but this fails

```
create table deid.testing
(
    column_1 integer not null
        constraint testing_pk
            primary key
);
```

**Comment by MichaelDBA** [comment]
I am able to confirm this happens on PG 13.  Working on it...

**Comment by MichaelDBA** [comment]
Try the latest code, v13 system table type defs are different in some cases than v14.

**Comment by MichaelDBA** [comment]
Since I haven't heard back from you, I am closing this as FIXED based on my tests.
